### ISSUE TITLE
schedule.run_pending(): TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by durapensa** [cognitivegears/CircuitPython_uschedule#1]
This error appears after the second call of schedule.run_pending(), using a setup similar to the provided example. 
Running on a Feather RP2040 w/`adafruit-circuitpython-adafruit_feather_rp2040-en_US-20210313-d2563c5` (post-6.2.0-beta3) & `CircuitPython_uschedule` from main.
Code & output with error message are in this gist of a jupyter notebook:
https://gist.github.com/durapensa/c8e533c27d514d12f21a121e3f3e58f4

**Comment by durapensa** [comment]
oops, scratch this. comparing revisions 3, 4 in the gist, I was calling `.do(method())` rather than `.do(method)`.

**Comment by cognitivegears** [comment]
I'm glad that this was resolved for you, but I'm actually going to keep this open to look at further as an issue - I've run into the same problem myself while testing this module, probably the code should check to make sure the parameter to do() is callable.

**Comment by cognitivegears** [comment]
Added the code check with 0.1.1, now it will no longer allow you to call do() with an argument that is not callable.
